export {default as cssLogo} from './css.png'
export {default as firebaseLogo } from './firebase.png'
export {default as githubLogo} from './github.png'
export {default as htmlLogo} from './html.png'
export {default as javascriptLogo} from './javascript.png'
export {default as mongoLogo} from './mongo.png'
export {default as nodeLogo} from './node.png'
export {default as pythonLogo} from './python.png'
export {default as reactLogo} from './react.png'
export {default as tailwindLogo} from './tailwind.png'
